let myDate= new Date()
console.log(myDate)
console.log(myDate.toDateString)
console.log(myDate.toISOString)
console.log(myDate.toJSON)
console.log(myDate.toLocaleDateString)
console.log(myDate.toLocaleTimeString)
console.log(myDate.toString)
console.log(myDate.toTimeString)
console.log(myDate.toUTCString)
console.log(myDate.getTime)
console.log(myDate.getTimezoneOffset)
console.log(myDate.setTime)